#datasource specific properties
spring:
   datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/practodb
    driver-class-name: com.mysql.cj.jdbc.Driver
#jpa properties
   jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
 
 

  
